# Build

name: build

on:
  # Run after synchronizing
  workflow_run:
    workflows:
      - sync
    types:
      - completed

  # Run when manually triggered
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Download module dependencies
        run: go mod download

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
          version: latest

      - name: Build
        run: ./build_dist.sh

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: tailscale-minified
          path: dist/*
          retention-days: 45